name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_ID: ultra-component-479316-a5 
  REGION: europe-southwest1
  REPOSITORY: t01g01-registry
  IMAGE_NAME: certificate-validation-pubsub
  REGISTRY: europe-southwest1-docker.pkg.dev
  BUCKET_NAME: made-in-portugal-certificates-pubsub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $REGISTRY --quiet

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Create Backend Bucket if missing
        run: |
          # 1. Check if the bucket exists
          if ! gcloud storage ls gs://$BUCKET_NAME > /dev/null 2>&1; then
            echo "Bucket $BUCKET_NAME does not exist. Creating it..."
            
            # 2. Create the bucket
            gcloud storage buckets create gs://$BUCKET_NAME \
              --project=$PROJECT_ID \
              --location=$REGION \
              --uniform-bucket-level-access
              
            echo "Bucket created successfully."
          else
            echo "Bucket $BUCKET_NAME already exists."
          fi

      - name: Terraform init & apply (infra)
        working-directory: infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          CLOUDSDK_CORE_PROJECT: ${{ env.PROJECT_ID }}
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false -var="project_id=${{ env.PROJECT_ID }}" -var="bucket_name=${{ env.BUCKET_NAME }}"

      - name: Define image tags
        id: vars
        run: |
          SHA_TAG=${GITHUB_SHA::7}
          echo "sha_tag=$SHA_TAG" >> $GITHUB_OUTPUT
          echo "image=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.vars.outputs.image }}:latest \
                       -t ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.sha_tag }} .

      - name: Push Docker images
        run: |
          docker push ${{ steps.vars.outputs.image }}:latest
          docker push ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.sha_tag }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy certificate-validation \
            --image ${{ steps.vars.outputs.image }}:latest \
            --region $REGION \
            --project $PROJECT_ID \
            --platform managed \
            --set-env-vars BUCKET_NAME=$BUCKET_NAME,PROJECT_ID=$PROJECT_ID \
            --quiet \
            --allow-unauthenticated

